### ISSUE TITLE
cpu usage is full even nothing receiving

### ISSUE THREAD

**Issue by hulucc** [shaoyuan1943/fastudp#2]
![image](https://user-images.githubusercontent.com/4343900/117537603-9fc1d380-b034-11eb-8928-e899d3bd6808.png)

**Comment by hulucc** [comment]
pprof
![image](https://user-images.githubusercontent.com/4343900/117537661-0d6dff80-b035-11eb-99e3-71fe3aea3877.png)

**Comment by shaoyuan1943** [comment]
fixed

**Comment by hi-glenn** [comment]
Hi, @hulucc 

What is the performance?  How many PPS can it achieve ？
